### ISSUE TITLE
Basic invocation fails with a GSON parse error

### ISSUE THREAD

**Issue by ZacSweers** [cdsap/TaskReport#2]
Was trying the below command but received an immediate failure with some GSON parsing

```
 ✘  ~/Downloads  ./taskreport --api-key .getoken --url=<our-url> --project=<project-name> --requested-task=:app:assembleInternalDebug --max-builds=2000 --tags=not:CI
Calculating Build Scans to retrieve
 50% ######################### /Exception in thread "main" io.ktor.serialization.JsonConvertException: Illegal json parameter found
	at io.ktor.serialization.gson.GsonConverter.deserialize(GsonConverter.kt:44)
	at io.ktor.serialization.gson.GsonConverter$deserialize$1.invokeSuspend(GsonConverter.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.github.cdsap.taskreport.TaskReportCli.run(main.kt:77)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at io.github.cdsap.taskreport.MainKt.main(main.kt:16)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.Gson.fromJson(Gson.java:956)
	at io.ktor.serialization.gson.GsonConverter$deserialize$2.invokeSuspend(GsonConverter.kt:41)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
	at com.google.gson.Gson.fromJson(Gson.java:991)
	... 10 more
```

**Comment by ZacSweers** [comment]
It looks like this is because `--api-key` expects the raw key, but the docs suggest this must be a file here: https://github.com/cdsap/TaskReport#complete-list-of-parameters

<img width="901" alt="image" src="https://github.com/cdsap/TaskReport/assets/1361086/3f11adcc-2889-4696-a76b-65d5359fa7ad">

**Comment by cdsap** [comment]
thanks for the report, updated the readme
